// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3wzNHBNiI25CWklDp6M5CH2zv9IrM6qA',
    appId: '1:536960875406:web:3cc0870a6718cc3eccc2df',
    messagingSenderId: '536960875406',
    projectId: 'housepal-app-2025',
    authDomain: 'housepal-app-2025.firebaseapp.com',
    storageBucket: 'housepal-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf6KNlbclWb74XFw1ZdRPRf7WLBT6MyY0',
    appId: '1:536960875406:android:cfba084d21db3a27ccc2df',
    messagingSenderId: '536960875406',
    projectId: 'housepal-app-2025',
    storageBucket: 'housepal-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHcfVW6gxU8nsoKfyWd6G2bYlUCkyA0a8',
    appId: '1:536960875406:ios:65b809c9174b167accc2df',
    messagingSenderId: '536960875406',
    projectId: 'housepal-app-2025',
    storageBucket: 'housepal-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.btlMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHcfVW6gxU8nsoKfyWd6G2bYlUCkyA0a8',
    appId: '1:536960875406:ios:65b809c9174b167accc2df',
    messagingSenderId: '536960875406',
    projectId: 'housepal-app-2025',
    storageBucket: 'housepal-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.btlMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3wzNHBNiI25CWklDp6M5CH2zv9IrM6qA',
    appId: '1:536960875406:web:a646ed6f5ba6359cccc2df',
    messagingSenderId: '536960875406',
    projectId: 'housepal-app-2025',
    authDomain: 'housepal-app-2025.firebaseapp.com',
    storageBucket: 'housepal-app-2025.firebasestorage.app',
  );
}
